name: Publish Chrome extension to Chrome Web Store

on:
    pull_request:
        branches: ["master"]

jobs:
    build:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install

            - name: Build & zip extension
              run: npm run zip

            - name: Upload to Chrome Web Store
              uses: mobilefirstllc/cws-publish@latest
              with:
                  action: "publish"
                  client_id: ${{ secrets.CLIENT }}
                  client_secret: ${{ secrets.SECRET }}
                  refresh_token: ${{ secrets.TOKEN }}
                  extension_id: ${{ secrets.EXTENSION_ID }}
                  zip_file: "./dist/extension.zip"
